### ISSUE TITLE
link rel="preconnect" href possibly wrong

### ISSUE THREAD

**Issue by N1GHTR4NG3R** [Andr3wRiv3rs/vue-fullstack-boilerplate#1] opened 2020-05-21 06:04 UTC

**Comment by AndresSweeneyRios** [comment] 2020-05-21 06:07
Why is this wrong? Is it introducing an issue?

**Comment by AndresSweeneyRios** [comment] 2020-05-21 06:13
Closing because this is an accidental duplicate of #2.

**Closed as completed by AndresSweeneyRios** 2020-05-21 06:13 UTC
